//=============================================================================
// RuneTranslateCheats — live in-game cheat menu (RPG Maker MV/MZ)
// Generated by RuneTranslate. Offline single-player use only.
//
// Pure DOM overlay + version-proof runtime globals ($gameParty, $gameSwitches,
// $gameVariables, $gameActors, $gamePlayer, $gameTroop, $dataItems, $dataSystem,
// BattleManager). No Scene_*/Window_* APIs, so the same code runs on MV and MZ.
//=============================================================================
(function () {
  'use strict';
  if (window.$RTCheats) return; // idempotent if the plugin is somehow loaded twice

  var HOTKEY = '__RT_HOTKEY__'; // substituted at export time, e.g. 'F10'

  var toggles = []; // { id, label, tick, on }   → rendered in the "Cheats" tab
  var actions = []; // { id, label, run }         → rendered in the "Cheats" tab
  var tabs = []; // { id, label, render }         → custom tabs (Variables, Switches…)
  var panel = null;
  var tabBar = null;
  var content = null;
  var activeTabId = 'cheats';
  var built = false;

  // api.tab must exist BEFORE window.$RTCheats is assigned so later-concatenated
  // payload modules can register their tabs.
  var api = {
    // A per-frame toggle cheat. tick() runs every frame while `on`.
    toggle: function (id, label, tick, defaultOn) {
      toggles.push({ id: id, label: label, tick: tick, on: !!defaultOn });
    },
    // A one-shot action, rendered as a button in the Cheats tab.
    action: function (id, label, run) {
      actions.push({ id: id, label: label, run: run });
    },
    // A custom tab. render(container) fills the tab; it is called FRESH every
    // time the tab is opened, so it always reflects current game state.
    tab: function (id, label, render) {
      tabs.push({ id: id, label: label, render: render });
    },
  };
  window.$RTCheats = api;

  function styleButton(b) {
    b.style.cssText =
      'display:block;width:100%;margin:3px 0;padding:5px 8px;background:#2a2a3a;color:#e6e6ff;' +
      'border:1px solid #44445a;border-radius:4px;cursor:pointer;font:12px monospace;text-align:left;';
    b.onmouseover = function () { b.style.background = '#3a3a52'; };
    b.onmouseout = function () { b.style.background = '#2a2a3a'; };
  }

  /** The "Cheats" tab: the toggle checkboxes + one-shot action buttons. */
  function renderCheatsTab(container) {
    toggles.forEach(function (t) {
      var lab = document.createElement('label');
      lab.style.cssText = 'display:flex;align-items:center;gap:6px;margin:4px 0;cursor:pointer;';
      var cb = document.createElement('input');
      cb.type = 'checkbox';
      cb.checked = t.on; // source of truth is t.on, so re-render reflects state
      cb.onchange = function () { t.on = cb.checked; };
      var span = document.createElement('span');
      span.textContent = t.label;
      lab.appendChild(cb);
      lab.appendChild(span);
      container.appendChild(lab);
    });
    actions.forEach(function (a) {
      var b = document.createElement('button');
      b.textContent = a.label;
      styleButton(b);
      b.onclick = function () { try { a.run(); } catch (e) {} };
      container.appendChild(b);
    });
  }

  function allTabs() {
    return [{ id: 'cheats', label: 'Cheats', render: renderCheatsTab }].concat(tabs);
  }

  function renderTabBar() {
    tabBar.innerHTML = '';
    allTabs().forEach(function (tb) {
      var b = document.createElement('button');
      b.textContent = tb.label;
      var activeBg = tb.id === activeTabId ? '#ff79c6' : '#2a2a3a';
      var activeFg = tb.id === activeTabId ? '#1a1a26' : '#e6e6ff';
      b.style.cssText =
        'padding:3px 8px;margin:0 3px 0 0;background:' + activeBg + ';color:' + activeFg + ';' +
        'border:1px solid #44445a;border-radius:4px;cursor:pointer;font:11px monospace;';
      b.onclick = function () { selectTab(tb.id); };
      tabBar.appendChild(b);
    });
  }

  function renderActiveTab() {
    var tab = allTabs().filter(function (t) { return t.id === activeTabId; })[0] || allTabs()[0];
    content.innerHTML = '';
    // A throwing tab (e.g. a transient null global) must not blank the whole panel.
    try {
      tab.render(content);
    } catch (e) {
      var err = document.createElement('div');
      err.textContent = 'This tab is unavailable right now.';
      err.style.cssText = 'opacity:0.6;font-size:11px;';
      content.appendChild(err);
    }
  }

  function selectTab(id) {
    activeTabId = id;
    renderTabBar();
    renderActiveTab();
  }

  function build() {
    if (built) return;
    built = true;
    panel = document.createElement('div');
    panel.style.cssText =
      'position:fixed;top:12px;right:12px;z-index:2147483647;width:300px;max-height:84vh;overflow:auto;' +
      'background:rgba(18,18,28,0.95);color:#e6e6ff;border:1px solid #555;border-radius:8px;padding:10px;' +
      'font:12px monospace;display:none;box-shadow:0 6px 24px rgba(0,0,0,0.5);';
    // Don't let the game see keystrokes typed into our inputs.
    panel.addEventListener('keydown', function (e) { e.stopPropagation(); }, false);

    var title = document.createElement('div');
    title.textContent = 'RuneTranslate Cheats';
    title.style.cssText = 'font-weight:bold;margin-bottom:2px;color:#ff79c6;';
    panel.appendChild(title);

    var hint = document.createElement('div');
    hint.textContent = 'Press ' + HOTKEY + ' to close · offline use only';
    hint.style.cssText = 'opacity:0.6;margin-bottom:8px;font-size:10px;';
    panel.appendChild(hint);

    tabBar = document.createElement('div');
    tabBar.style.cssText = 'display:flex;flex-wrap:wrap;gap:2px;margin-bottom:8px;';
    panel.appendChild(tabBar);

    content = document.createElement('div');
    panel.appendChild(content);

    document.body.appendChild(panel);
    selectTab(activeTabId);
  }

  function togglePanel() {
    build();
    var show = panel.style.display === 'none';
    panel.style.display = show ? 'block' : 'none';
    // Re-render the active tab on open so listed values are always current.
    if (show) renderActiveTab();
  }

  document.addEventListener(
    'keydown',
    function (e) {
      if (e.key === HOTKEY) {
        e.preventDefault();
        e.stopPropagation();
        togglePanel();
      }
    },
    true,
  );

  function loop() {
    for (var i = 0; i < toggles.length; i++) {
      if (toggles[i].on) {
        try { toggles[i].tick(); } catch (e) {}
      }
    }
    requestAnimationFrame(loop);
  }
  requestAnimationFrame(loop);
})();
