#!/usr/bin/env python3
"""
Universal RPG Maker MV/MZ Translation Restoration Script
========================================================

Reverts translation-induced corruption by cross-referencing translated JSON
against original Japanese JSON. Follows engine-standard command-code rules.

Usage:
    python restore_rpgmaker.py <data_original_dir> <data_translated_dir> [config_path]

    python restore_rpgmaker.py ./data_original ./data_translated restore_config.json

Engine-Standard Rules (applied generically):
  - Code 401/405/102 (Show Text / Choices):        KEPT translated (dialogue)
  - Code 357/355/655 (Plugin Commands / Scripts): REVERT to original
  - Code 250/251/231 (Audio / Picture filenames): REVERT filename params

All plugin-specific param names and regex patterns are externalized
in the config JSON file (default: restore_config.json in same directory).

Works with both RPG Maker MV and MZ event command formats.
"""

import json
import os
import re
import sys
import argparse
import fnmatch
import copy
from typing import Any


class RPGMakerRestorer:
    """Cross-references translated RPG Maker JSON data against originals."""

    # Engine-standard command codes
    KEEP_TRANSLATED_CODES = {401, 405, 102}
    REVERT_FULL_COMMAND_CODES = {357, 355, 655}
    REVERT_FILENAME_CODES = {250, 251, 231}

    def __init__(self, original_dir: str, translated_dir: str, config_path: str, dry_run: bool = False):
        self.original_dir = os.path.abspath(original_dir)
        self.translated_dir = os.path.abspath(translated_dir)
        self.config_path = os.path.abspath(config_path)
        self.config = self._load_json(self.config_path)
        self.dry_run = dry_run
        self.stats = {
            'files_processed': 0,
            'files_restored': 0,
            'commands_reverted': 0,
            'filename_params_restored': 0,
            'plugin_params_protected': 0,
            'forced_replacements': 0,
            'warnings': 0,
        }
        self._validate_dirs()

    def _validate_dirs(self):
        if not os.path.isdir(self.original_dir):
            raise FileNotFoundError(f"Original data directory not found: {self.original_dir}")
        if not os.path.isdir(self.translated_dir):
            raise FileNotFoundError(f"Translated data directory not found: {self.translated_dir}")
        if not os.path.isfile(self.config_path):
            raise FileNotFoundError(f"Config file not found: {self.config_path}")

        print(f"Original:   {self.original_dir}")
        print(f"Translated: {self.translated_dir}")
        print(f"Config:     {self.config_path}")
        print()

    def _load_json(self, path: str) -> Any:
        with open(path, 'r', encoding='utf-8') as f:
            content = f.read()
        
        # Handle plugins.js/plugins.js_bak which starts with "var $plugins = "
        if path.endswith('.js') or path.endswith('.js_bak') or 'var $plugins =' in content:
            start = content.find('[')
            end = content.rfind(']') + 1
            if start != -1 and end != -1:
                return json.loads(content[start:end])
        
        return json.loads(content)

    def _save_json(self, path: str, data: Any) -> None:
        with open(path, 'w', encoding='utf-8', newline='\n') as f:
            if path.endswith('.js') or path.endswith('.js_bak'):
                f.write('// Generated by RPG Maker.\n// Do not edit this file directly.\nvar $plugins =\n')
                json.dump(data, f, ensure_ascii=False, indent=2)
                f.write(';\n')
            else:
                json.dump(data, f, ensure_ascii=False, indent=1)
                f.write('\n')

    def _get_plugin_param_protection(self, plugin_name: str) -> list:
        """Get protected param names for a plugin from config."""
        protection = self.config.get('plugin_param_protection', {})
        if plugin_name in protection:
            entry = protection[plugin_name]
            if isinstance(entry, dict):
                return entry.get('protected_params', [])
            if isinstance(entry, list):
                return entry
        default = protection.get('_default', {})
        if isinstance(default, dict):
            return default.get('protected_params', [])
        return []

    def run(self):
        """Process all matching JSON files in translated directory."""
        patterns = self.config.get('files_to_process', [])
        all_files = []

        for pattern in patterns:
            matched = []
            for root, _, files in os.walk(self.translated_dir):
                for fname in files:
                    if fnmatch.fnmatch(fname, pattern):
                        matched.append(os.path.join(root, fname))
            all_files.extend(sorted(matched))

        all_files = sorted(set(all_files))
        print(f"Found {len(all_files)} files to process.\n")

        for trans_path in all_files:
            rel_path = os.path.relpath(trans_path, self.translated_dir)
            orig_path = os.path.join(self.original_dir, rel_path)

            if not os.path.isfile(orig_path):
                print(f"  SKIP (no original): {rel_path}")
                self.stats['warnings'] += 1
                continue

            try:
                trans_data = self._load_json(trans_path)
                orig_data = self._load_json(orig_path)
            except (json.JSONDecodeError, UnicodeDecodeError) as e:
                print(f"  ERROR (invalid JSON): {rel_path} - {e}")
                self.stats['warnings'] += 1
                continue

            original_before = copy.deepcopy(trans_data)
            restored_data = self._process_file(trans_data, orig_data, rel_path)

            if restored_data != original_before:
                if not self.dry_run:
                    self._save_json(trans_path, restored_data)
                self.stats['files_restored'] += 1
                status = "DRY-RUN would restore" if self.dry_run else "RESTORED"
                print(f"  {status}: {rel_path}")
            else:
                print(f"  OK (no changes): {rel_path}")

            self.stats['files_processed'] += 1

            self._print_summary()

    def run_standalone(self):
        """Apply only generic forced string replacements, no backup diff."""
        patterns = self.config.get('files_to_process', [])
        all_files = []
        for pattern in patterns:
            matched = []
            for root, _, files in os.walk(self.translated_dir):
                for fname in files:
                    if fnmatch.fnmatch(fname, pattern):
                        matched.append(os.path.join(root, fname))
            all_files.extend(sorted(matched))
        all_files = sorted(set(all_files))
        print(f"[Standalone] Found {len(all_files)} files to process.\n")

        for trans_path in all_files:
            rel_path = os.path.relpath(trans_path, self.translated_dir)
            try:
                data = self._load_json(trans_path)
            except Exception as e:
                print(f"  SKIP (invalid JSON): {rel_path} - {e}")
                self.stats['warnings'] += 1
                continue

            original_before = copy.deepcopy(data)
            self._apply_forced_replacements(data, rel_path)

            if data != original_before:
                if not self.dry_run:
                    self._save_json(trans_path, data)
                self.stats['files_restored'] += 1
                print(f"  {'DRY-RUN would restore' if self.dry_run else 'RESTORED'}: {rel_path}")
            else:
                print(f"  OK (no changes): {rel_path}")
            self.stats['files_processed'] += 1

        self._print_summary()

    def _process_file(self, trans_data: Any, orig_data: Any, rel_path: str) -> Any:
        """Dispatch to the appropriate processor based on file type."""
        fname = os.path.basename(rel_path)

        if fnmatch.fnmatch(fname, 'Map*.json'):
            return self._process_map_file(trans_data, orig_data, rel_path)
        elif fname == 'CommonEvents.json':
            return self._process_common_events(trans_data, orig_data, rel_path)
        elif fname == 'System.json':
            return self._process_system_file(trans_data, orig_data, rel_path)
        elif fname in ('plugins.js', 'plugins.js_bak'):
            return self._process_plugins_file(trans_data, orig_data, rel_path)
        else:
            return self._process_generic_file(trans_data, orig_data)
    def _process_plugins_file(self, trans_data: Any, orig_data: Any, rel_path: str = None) -> Any:
        """Process plugins.js - restore plugin parameters."""
        result = copy.deepcopy(trans_data)
        if not isinstance(result, list) or not isinstance(orig_data, list):
            return result

        for i, plugin in enumerate(result):
            if i < len(orig_data):
                orig_plugin = orig_data[i]
                if isinstance(plugin, dict) and isinstance(orig_plugin, dict):
                    plugin_name = plugin.get('name', '')
                    result[i] = self._restore_plugin_params(
                        plugin, orig_plugin, plugin_name
                    )

        # Apply forced string replacements (PT-BR -> Japanese)
        self._apply_forced_replacements(result, rel_path)

        return result

    def _process_map_file(self, trans_data: Any, orig_data: Any, rel_path: str = None) -> Any:
        """Process MapXXX.json - restore event commands."""
        result = copy.deepcopy(trans_data)

        if 'events' not in result or not result['events']:
            return result

        trans_events = result['events']
        orig_events = orig_data.get('events', []) if isinstance(orig_data, dict) else []

        if isinstance(trans_events, list):
            for i, event in enumerate(trans_events):
                if event is None:
                    continue
                if i < len(orig_events) and orig_events[i] is not None:
                    orig_event = orig_events[i]
                    for p_idx, page in enumerate(event.get('pages', [])):
                        orig_pages = orig_event.get('pages', [])
                        if p_idx < len(orig_pages) and orig_pages[p_idx] is not None:
                            orig_page = orig_pages[p_idx]
                            if 'list' in page and 'list' in orig_page:
                                page['list'] = self._restore_event_commands(
                                    page['list'], orig_page['list']
                                )
        elif isinstance(trans_events, dict):
            for event_id, event in trans_events.items():
                if event is None:
                    continue
                # If original is a list, look up by int ID, otherwise by key string
                orig_event = None
                if isinstance(orig_events, list):
                    try:
                        idx = int(event_id)
                        if idx < len(orig_events):
                            orig_event = orig_events[idx]
                    except ValueError:
                        pass
                elif isinstance(orig_events, dict):
                    orig_event = orig_events.get(event_id)

                if not orig_event:
                    continue

                for p_idx, page in enumerate(event.get('pages', [])):
                    orig_pages = orig_event.get('pages', [])
                    if p_idx < len(orig_pages) and orig_pages[p_idx] is not None:
                        orig_page = orig_pages[p_idx]
                        if 'list' in page and 'list' in orig_page:
                            page['list'] = self._restore_event_commands(
                                page['list'], orig_page['list']
                            )

        # Apply forced string replacements (PT-BR -> Japanese)
        self._apply_forced_replacements(result, rel_path)

        return result

    def _process_common_events(self, trans_data: Any, orig_data: Any, rel_path: str = None) -> Any:
        """Process CommonEvents.json - restore event command lists."""
        result = copy.deepcopy(trans_data)
        
        # In MV/MZ, CommonEvents.json is a JSON array [null, event1, event2, ...]
        # but sometimes it can be wrapped as an object. Handle both.
        trans_events = result if isinstance(result, list) else result.get('commonEvents', [])
        orig_events = orig_data if isinstance(orig_data, list) else orig_data.get('commonEvents', [])

        for i, event in enumerate(trans_events):
            if event is None: continue
            if i < len(orig_events) and orig_events[i] is not None:
                orig_event = orig_events[i]
                if 'list' in event and 'list' in orig_event:
                    event['list'] = self._restore_event_commands(
                        event['list'], orig_event['list']
                    )

        # Apply forced string replacements (PT-BR -> Japanese)
        self._apply_forced_replacements(result, rel_path)

        return result

    def _restore_event_commands(self, trans_list: list, orig_list: list) -> list:
        """Compare event command lists and revert engine-protected codes."""
        result = list(trans_list)

        max_len = min(len(result), len(orig_list))
        for i in range(max_len):
            trans_cmd = result[i]
            orig_cmd = orig_list[i]

            if not isinstance(trans_cmd, dict) or not isinstance(orig_cmd, dict):
                continue

            code = trans_cmd.get('code')

            # Skip non-matching codes (structure change)
            if orig_cmd.get('code') != code:
                continue

            # Codes 401/405/102: keep translated, only fix nested params
            if code in self.KEEP_TRANSLATED_CODES:
                result[i] = self._restore_text_command_params(trans_cmd, orig_cmd)
                continue

            # Codes 357/355/655: revert entire command
            if code in self.REVERT_FULL_COMMAND_CODES:
                if trans_cmd != orig_cmd:
                    result[i] = copy.deepcopy(orig_cmd)
                    self.stats['commands_reverted'] += 1
                continue

            # Codes 250/251/231: revert filename params
            if code in self.REVERT_FILENAME_CODES:
                result[i] = self._restore_filename_command(result[i], orig_cmd)
                continue

        return result

    def _restore_text_command_params(self, trans_cmd: dict, orig_cmd: dict) -> dict:
        """
        For Show Text / Show Choices commands (codes 401/405/102):
        Keep translated text, but revert any embedded file-name-like params
        that should reference original assets.
        """
        result = copy.deepcopy(trans_cmd)
        code = result.get('code')

        # Code 102 (Show Choices) - params are choice strings; keep them translated
        if code == 102:
            return result

        # Codes 401/405 - parameters are [faceName, faceIndex, message, ...]
        # Face name (index 0) and message (index 2) should be handled:
        #   faceName -> revert if it looks like an image filename reference
        #   message  -> keep translated
        params = result.get('parameters', [])
        orig_params = orig_cmd.get('parameters', [])
        if len(params) >= 1 and isinstance(params[0], str) and len(orig_params) >= 1:
            face_name = params[0]
            if face_name and face_name != orig_params[0]:
                # Check if it looks like a face filename reference
                if self._looks_like_filename(face_name):
                    params[0] = orig_params[0]
                    self.stats['filename_params_restored'] += 1

        return result

    def _restore_filename_command(self, trans_cmd: dict, orig_cmd: dict) -> dict:
        """Revert filename params in Audio/Picture commands (codes 250/251/231).

        For these codes, the param is ALWAYS a filename reference by engine
        definition. If it differs from the original, revert it unconditionally.
        """
        code = trans_cmd.get('code')
        param_index = self.REVERT_FILENAME_CODES_PARAM_INDEX.get(str(code), 0)

        params = list(trans_cmd.get('parameters', []))
        orig_params = list(orig_cmd.get('parameters', []))

        if param_index < len(params) and param_index < len(orig_params):
            trans_filename = params[param_index]
            orig_filename = orig_params[param_index]

            if trans_filename != orig_filename:
                params[param_index] = orig_filename
                self.stats['filename_params_restored'] += 1

        result = copy.deepcopy(trans_cmd)
        result['parameters'] = params
        return result

    # Engine-standard regex patterns for detecting asset file references
    _AUDIO_EXT_RE = re.compile(
        r'[\\/](?:[\w\-]+)\.(ogg|m4a|wav|mp3)$', re.IGNORECASE
    )
    _PICTURE_EXT_RE = re.compile(
        r'[\\/](?:[\w\-\[\] ]+)\.(png|jpg|jpeg|gif|bmp)$', re.IGNORECASE
    )
    _FILENAME_EXT_RE = re.compile(
        r'\.(png|jpg|jpeg|gif|bmp|ogg|m4a|wav|mp3)$', re.IGNORECASE
    )

    def _looks_like_filename(self, s: str) -> bool:
        """Detect if a string looks like a transliterated asset filename."""
        if not s:
            return False
        # Check for path separator + known asset extension
        if re.search(r'[\\/]', s):
            if self._FILENAME_EXT_RE.search(s):
                return True
        # Also check standalone file extensions without separators
        if s.startswith('audio/') or s.startswith('img/'):
            if self._FILENAME_EXT_RE.search(s):
                return True
        return False

    def _process_system_file(self, trans_data: Any, orig_data: Any, rel_path: str = None) -> Any:
        """Process System.json - restore plugin parameters and protected sections."""
        result = copy.deepcopy(trans_data)

        # Restore plugin parameters in the `system.plugins` array
        if 'system' in result and isinstance(result['system'], dict):
            sys_plugins = result['system'].get('plugins', [])
            orig_sys_plugins = orig_data.get('system', {}).get('plugins', [])

            for i, plugin in enumerate(sys_plugins):
                if i < len(orig_sys_plugins):
                    orig_plugin = orig_sys_plugins[i]
                    if isinstance(plugin, dict) and isinstance(orig_plugin, dict):
                        plugin_name = plugin.get('name', '')
                        result['system']['plugins'][i] = self._restore_plugin_params(
                            plugin, orig_plugin, plugin_name
                        )

        # Restore protected system sections
        sys_protect = self.config.get('system_json_protection', {})
        protected_sections = sys_protect.get('protected_sections', [])

        for section in protected_sections:
            if isinstance(section, str):
                if section in result and section in orig_data:
                    if result[section] != orig_data[section]:
                        result[section] = copy.deepcopy(orig_data[section])
                        self.stats['plugin_params_protected'] += 1
            elif isinstance(section, dict):
                for section_name, protected_keys in section.items():
                    if section_name in result and isinstance(result[section_name], dict):
                        orig_section = orig_data.get(section_name, {})
                        for key in protected_keys:
                            if key in result[section_name] and key in orig_section:
                                if result[section_name][key] != orig_section[key]:
                                    result[section_name][key] = copy.deepcopy(orig_section[key])
                                    self.stats['plugin_params_protected'] += 1

        # Apply forced string replacements (PT-BR -> Japanese) if configured
        self._apply_forced_replacements(result, rel_path)

        return result

    def _apply_forced_replacements(self, data: Any, rel_path: str) -> None:
        """Apply forced string replacements bypassing backup comparison.
        Used when backup files are NOT true original Japanese (already contain PT-BR).
        Applies generic_patterns first (multi-language), then game-specific overrides."""
        fsr = self.config.get('forced_string_replacements', {})
        if not fsr.get('enabled', False):
            return

        # 0. Check if any game config explicitly disables generic menu_choices
        games_config = fsr.get('games', {})
        skip_generic_menu_choices = False
        for game_key, game_cfg in games_config.items():
            if game_key.startswith('_') or game_key == 'enabled':
                continue
            if game_cfg.get('disable_generic_menu_choices', False):
                skip_generic_menu_choices = True
                break

        # 1. Apply GENERIC patterns (all languages) to ANY game automatically
        generic = fsr.get('generic_patterns', {})
        if generic:
            self._apply_generic_patterns(data, rel_path, generic, skip_generic_menu_choices)

        # 2. Apply game-specific overrides
        for game_key, game_cfg in games_config.items():
            if game_key.startswith('_') or game_key == 'enabled':
                continue
            applies = False
            for attr in ['system_json', 'plugins.js', 'map_files']:
                if attr in game_cfg:
                    applies = True
                    break
            if not applies:
                continue

            if rel_path == 'System.json' and 'system_json' in game_cfg:
                self._apply_system_json_replacements(data, game_cfg['system_json'])

            if rel_path in ('plugins.js', 'plugins.js_bak') and 'plugins.js' in game_cfg:
                self._apply_plugins_js_replacements(data, game_cfg['plugins.js'])

            if rel_path in game_cfg.get('map_files', {}):
                map_cfg = game_cfg['map_files'][rel_path]
                self._apply_map_file_replacements(data, map_cfg)

            if rel_path == 'CommonEvents.json' and 'common_events' in game_cfg:
                self._apply_common_events_replacements(data, game_cfg['common_events'])

    def _apply_generic_patterns(self, data: Any, rel_path: str, generic_cfg: dict,
                                skip_menu_choices: bool = False) -> None:
        """Apply generic multi-language patterns to any game automatically.
        Detects PT/ES/FR/DE/IT UI strings in System.json and replaces them with Japanese.
        If skip_menu_choices is True, skip the generic menu_choices PT->JP restore
        (used by games where title screen choices should remain in the target language)."""
        # Apply to System.json - detect language and replace terms
        if rel_path == 'System.json':
            terms = data.get('terms', {}) if isinstance(data, dict) else {}
            # Preserve translated terms.commands and terms.messages in target language (PT/ES/FR/etc)
            return


            languages = generic_cfg.get('languages', {})
            if not languages:
                return

            # Build case-insensitive lookup for commands
            cmd_maps_ci = {}
            for lang_code, lang_cfg in languages.items():
                raw = lang_cfg.get('terms.commands', {})
                cmd_maps_ci[lang_code] = {k.lower(): v for k, v in raw.items()}

            # Replace commands (case-insensitive, preserve original case in output)
            commands = terms.get('commands', [])
            if isinstance(commands, list):
                for i, cmd in enumerate(commands):
                    if not isinstance(cmd, str):
                        continue
                    for lang_code, cmd_map_ci in cmd_maps_ci.items():
                        mapped = cmd_map_ci.get(cmd.lower())
                        if mapped:
                            commands[i] = mapped
                            self.stats['forced_replacements'] = self.stats.get('forced_replacements', 0) + 1
                            break

            # Build case-insensitive lookup for messages
            msg_maps_ci = {}
            for lang_code, lang_cfg in languages.items():
                raw = lang_cfg.get('terms.messages', {})
                msg_maps_ci[lang_code] = {k.lower(): v for k, v in raw.items()}

            # Replace messages (case-insensitive)
            messages = terms.get('messages', {})
            if isinstance(messages, dict):
                for key in list(messages.keys()):
                    val = messages.get(key)
                    if not isinstance(val, str):
                        continue
                    for lang_code, msg_map_ci in msg_maps_ci.items():
                        mapped = msg_map_ci.get(val.lower())
                        if mapped:
                            messages[key] = mapped
                            self.stats['forced_replacements'] = self.stats.get('forced_replacements', 0) + 1
                            break

        # Apply generic menu choices to map files (unless disabled for this game)
        if not skip_menu_choices and rel_path and rel_path.startswith('Map') and rel_path.endswith('.json'):
            menu_choices = generic_cfg.get('menu_choices', {})
            if menu_choices:
                # Build case-insensitive choice maps
                lang_choices_ci = {}
                for lang_code, choices in menu_choices.items():
                    lang_choices_ci[lang_code] = {k.lower(): v for k, v in choices.items()}

                events = data.get('events', []) if isinstance(data, dict) else []
                for event in events:
                    if not isinstance(event, dict) or event is None:
                        continue
                    for page in event.get('pages', []) if isinstance(event, dict) else []:
                        if not isinstance(page, dict):
                            continue
                        for cmd in page.get('list', []):
                            if not isinstance(cmd, dict):
                                continue
                            code = cmd.get('code')
                            params = cmd.get('parameters', [])
                            # Code 102 = Show Choices
                            if code == 102 and isinstance(params, list) and len(params) > 0:
                                if isinstance(params[0], list):
                                    for i, choice in enumerate(params[0]):
                                        if isinstance(choice, str):
                                            for lang_code, choices_ci in lang_choices_ci.items():
                                                mapped = choices_ci.get(choice.lower())
                                                if mapped:
                                                    params[0][i] = mapped
                                                    self.stats['forced_replacements'] = self.stats.get('forced_replacements', 0) + 1
                                                    break

        # Apply generic title patterns and cursor patterns ONLY to display-
        # strings visible to the player (Show Text 401, Show Choices 102,
        # Message FaceName, etc.). NEVER touch technical strings like
        # plugin command params (357/655), scripts (355/657), variable names,
        # switch names, or any identifier — avoids corrupting game data refs.
        if rel_path and fnmatch.fnmatch(os.path.basename(rel_path), 'Map*.json'):
            title_patterns = generic_cfg.get('generic_title_patterns', {})
            cursor_patterns = generic_cfg.get('generic_cursor_patterns', {})
            if not title_patterns and not cursor_patterns:
                return
            # Sort by length desc to avoid partial-substring collision
            title_rules = sorted(title_patterns.items(), key=lambda x: len(x[0]), reverse=True)
            cursor_rules = sorted(cursor_patterns.items(), key=lambda x: len(x[0]), reverse=True)

            def apply_ui_rules(s):
                if not isinstance(s, str):
                    return s
                result = s
                for old, new in title_rules:
                    if old in result:
                        result = result.replace(old, new)
                        self.stats['forced_replacements'] = self.stats.get('forced_replacements', 0) + 1
                for old, new in cursor_rules:
                    if old in result:
                        result = result.replace(old, new)
                        self.stats['forced_replacements'] = self.stats.get('forced_replacements', 0) + 1
                return result

            events = data.get('events', []) if isinstance(data, dict) else []
            for event in events:
                if not isinstance(event, dict):
                    continue
                for page in event.get('pages', []) if isinstance(event, dict) else []:
                    if not isinstance(page, dict):
                        continue
                    for cmd in page.get('list', []):
                        if not isinstance(cmd, dict):
                            continue
                        code = cmd.get('code')
                        params = cmd.get('parameters', [])
                        # Skip technical commands entirely
                        if code in (355, 655, 357, 356, 108, 408, 111, 122, 123, 231, 232, 281, 241, 245, 249, 250, 132, 133, 139, 322, 323):
                            continue
                        # 401 Show Text: params[0] = text
                        if code == 401 and isinstance(params, list) and len(params) > 0:
                            params[0] = apply_ui_rules(params[0])
                        # 405 Change Message: params[0] = text (MZ)
                        # 102 Show Choices: params[0] = choices list
                        if code == 102 and isinstance(params, list) and len(params) > 0:
                            if isinstance(params[0], list):
                                params[0] = [apply_ui_rules(c) for c in params[0]]
                        # 415 Change Name: params[1] = name (MZ)
                        if code == 415 and isinstance(params, list) and len(params) > 1:
                            params[1] = apply_ui_rules(params[1])
                        # 205 Change Map Name is not user-string in params


    def _apply_system_json_replacements(self, data: Any, sys_cfg: dict) -> None:
        """Apply forced string replacements to System.json terms."""
        terms = data.get('terms', {})
        # Replace commands
        cmd_map = sys_cfg.get('terms.commands', {})
        cmd_map_ci = {k.lower(): v for k, v in cmd_map.items()}
        commands = terms.get('commands', [])
        for i, cmd in enumerate(commands):
            if isinstance(cmd, str):
                mapped = cmd_map_ci.get(cmd.lower())
                if mapped:
                    commands[i] = mapped
                    self.stats['forced_replacements'] = self.stats.get('forced_replacements', 0) + 1
        # Replace messages
        msg_map = sys_cfg.get('terms.messages', {})
        msg_map_ci = {k.lower(): v for k, v in msg_map.items()}
        messages = terms.get('messages', {})
        for key in list(messages.keys()):
            val = messages.get(key)
            if isinstance(val, str):
                mapped = msg_map_ci.get(val.lower())
                if mapped:
                    messages[key] = mapped
                    self.stats['forced_replacements'] = self.stats.get('forced_replacements', 0) + 1

    def _apply_plugins_js_replacements(self, data: Any, plugins_cfg: dict) -> None:
        """Apply forced string replacements within plugin parameters."""
        if not isinstance(data, list):
            return
        for plugin in data:
            if not isinstance(plugin, dict):
                continue
            pname = plugin.get('name', '')
            if pname not in plugins_cfg:
                continue
            plugin_cfg = plugins_cfg[pname]
            params = plugin.get('parameters', {})
            for param_key, replacements in plugin_cfg.items():
                if param_key not in params:
                    continue
                val = params[param_key]
                if not isinstance(val, str):
                    continue
                for old, new in sorted(replacements.items(), key=lambda x: len(x[0]), reverse=True):
                    if old in val:
                        val = val.replace(old, new)
                        self.stats['forced_replacements'] = self.stats.get('forced_replacements', 0) + 1
                params[param_key] = val

    def _apply_common_events_replacements(self, data: Any, ce_cfg: dict) -> None:
        """Apply forced string replacements within CommonEvents.json.
        Handles plugin command strings and map/event display names."""
        if not isinstance(data, list):
            return

        skel_map = ce_cfg.get('skeleton_name_replacements', {})
        map_map = ce_cfg.get('map_name_replacements', {})
        prefixes = ce_cfg.get('plugin_command_prefixes', [])

        for event in data:
            if event is None:
                continue
            if not isinstance(event, dict):
                continue
            # CommonEvents.json uses event.list[] (no pages).
            # Map events use event.pages[].list[]. Handle both.
            cmd_lists = []
            if 'list' in event and isinstance(event['list'], list):
                cmd_lists.append(event['list'])
            for page in event.get('pages', []) or []:
                if isinstance(page, dict) and isinstance(page.get('list'), list):
                    cmd_lists.append(page['list'])
            for cmd_list in cmd_lists:
                for cmd in cmd_list:
                    if not isinstance(cmd, dict):
                        continue
                    params = cmd.get('parameters', [])
                    for i, param in enumerate(params):
                        if isinstance(param, str):
                            changed = False
                            # Replace skeleton names
                            for old, new in sorted(skel_map.items(), key=lambda x: len(x[0]), reverse=True):
                                if old in param:
                                    param = param.replace(old, new)
                                    self.stats['forced_replacements'] = self.stats.get('forced_replacements', 0) + 1
                                    changed = True
                            # Replace map names
                            for old, new in sorted(map_map.items(), key=lambda x: len(x[0]), reverse=True):
                                if old in param:
                                    param = param.replace(old, new)
                                    self.stats['forced_replacements'] = self.stats.get('forced_replacements', 0) + 1
                                    changed = True
                            if changed:
                                params[i] = param

        # Also apply to Map name references within CommonEvents strings
        # (e.g., "Mapa da Casa de Praia" -> "海の家")

    def _apply_map_file_replacements(self, data: Any, map_cfg: dict) -> None:
        """Apply forced string replacements within Map JSON files."""
        def deep_replace(obj):
            if isinstance(obj, str):
                for attr, mapping in map_cfg.items():
                    for old, new in sorted(mapping.items(), key=lambda x: len(x[0]), reverse=True):
                        if old in obj:
                            obj = obj.replace(old, new)
                            self.stats['forced_replacements'] = self.stats.get('forced_replacements', 0) + 1
                return obj
            elif isinstance(obj, dict):
                return {k: deep_replace(v) for k, v in obj.items()}
            elif isinstance(obj, list):
                return [deep_replace(item) for item in obj]
            return obj
        # Only apply to specific keys
        menu_choices = map_cfg.get('menu_choices', {})
        image_filenames = map_cfg.get('image_filenames', {})
        if not menu_choices and not image_filenames:
            return
        # Walk through events looking for choice strings and image filename strings
        events = data.get('events', []) if isinstance(data, dict) else []
        for event in events:
            if event is None:
                continue
            for page in event.get('pages', []) if isinstance(event, dict) else []:
                for cmd in page.get('list', []) if isinstance(page, dict) else []:
                    self._apply_cmd_replacements(cmd, menu_choices, image_filenames)

    def _apply_cmd_replacements(self, cmd, menu_choices, image_filenames):
        """Apply replacements within an event command."""
        if not isinstance(cmd, dict):
            return
        code = cmd.get('code')
        params = cmd.get('parameters', [])
        if code == 102 and isinstance(params, list) and len(params) > 0:
            # Show Choices - params[0] is a list of choice strings
            if isinstance(params[0], list):
                for i, choice in enumerate(params[0]):
                    if isinstance(choice, str):
                        for pt, jp in menu_choices.items():
                            if choice == pt:
                                params[0][i] = jp
                                self.stats['forced_replacements'] = self.stats.get('forced_replacements', 0) + 1
        # Also check all string params for image filename patterns
        for i, param in enumerate(params):
            if isinstance(param, str):
                for pt, jp in image_filenames.items():
                    if pt in param:
                        params[i] = param.replace(pt, jp)
                        self.stats['forced_replacements'] = self.stats.get('forced_replacements', 0) + 1
            elif isinstance(param, str):
                pass  # already handled
            elif isinstance(param, dict):
                # Handle dict params that may contain JSON strings (e.g., OnevASSISTANT setImageChoices)
                for k, v in list(param.items()):
                    if isinstance(v, str):
                        new_val = v
                        changed = False
                        for pt, jp in image_filenames.items():
                            if pt in new_val:
                                new_val = new_val.replace(pt, jp)
                                self.stats['forced_replacements'] = self.stats.get('forced_replacements', 0) + 1
                                changed = True
                        for pt, jp in menu_choices.items():
                            if pt in new_val:
                                new_val = new_val.replace(pt, jp)
                                self.stats['forced_replacements'] = self.stats.get('forced_replacements', 0) + 1
                                changed = True
                        if changed:
                            param[k] = new_val
                    elif isinstance(v, str):
                        pass
                # Recursively handle nested dicts/lists
                for k, v in param.items():
                    if isinstance(v, dict):
                        self._apply_cmd_replacements(
                            {'code': code, 'parameters': [v]}, menu_choices, image_filenames
                        )
                    elif isinstance(v, list):
                        for item in v:
                            if isinstance(item, dict):
                                self._apply_cmd_replacements(
                                    {'code': code, 'parameters': [item]}, menu_choices, image_filenames
                                )

    def _parse_json_string(self, s: str) -> Optional[Any]:
        """Safely parse a string as JSON."""
        try:
            return json.loads(s)
        except json.JSONDecodeError:
            return None

    def _serialize_json_string(self, obj: Any) -> str:
        """Safely serialize an object back to a JSON string."""
        return json.dumps(obj, ensure_ascii=False)

    def _get_nested_param_protection(self, plugin_name: str, param_key: str) -> Optional[list]:
        """Get nested protected keys for a specific plugin and parameter from config."""
        protection = self.config.get('nested_plugin_param_protection', {})
        plugin_rules = protection.get(plugin_name, {})
        return plugin_rules.get(param_key)

    def _restore_plugin_params(self, trans_plugin: dict, orig_plugin: dict,
                               plugin_name: str) -> dict:
        """
        Restore plugin parameters, handling both direct keys and nested JSON strings.
        """
        result = copy.deepcopy(trans_plugin)
        direct_protected_names = set(self._get_plugin_param_protection(plugin_name))

        trans_params = result.get('parameters', {})
        orig_params = orig_plugin.get('parameters', {})

        for key in list(trans_params.keys()):
            orig_value = orig_params.get(key)
            trans_value = trans_params[key]

            # 1. Direct parameter protection (for MZ-style structured params)
            if key in direct_protected_names:
                if orig_value is not None and trans_value != orig_value:
                    result['parameters'][key] = copy.deepcopy(orig_value)
                    self.stats['plugin_params_protected'] += 1
                continue # Already handled, move to next parameter

            # 2. Check for nested JSON strings within parameters (e.g., in OnevASSISTANT)
            nested_protected_keys = self._get_nested_param_protection(plugin_name, key)
            if isinstance(trans_value, str) and nested_protected_keys is not None:
                parsed_trans = self._parse_json_string(trans_value)
                parsed_orig = self._parse_json_string(orig_value) if isinstance(orig_value, str) else None

                if parsed_trans is not None and parsed_orig is not None:
                    restored_nested_data = self._restore_nested_json_params(
                        parsed_trans, parsed_orig, set(nested_protected_keys), plugin_name=plugin_name, parent_key=key
                    )
                    serialized_restored = self._serialize_json_string(restored_nested_data)
                    if serialized_restored != trans_value:
                        result['parameters'][key] = serialized_restored
                        self.stats['plugin_params_protected'] += 1

            # 3. Handle MZ-style nested dict/list parameters (non-stringified JSON)
            elif isinstance(trans_value, dict) and isinstance(orig_value, dict):
                result['parameters'][key] = self._restore_nested_plugin_params(
                    trans_value, orig_value, direct_protected_names, plugin_name=plugin_name, parent_key=key
                )
            elif isinstance(trans_value, list) and isinstance(orig_value, list):
                new_list = []
                list_changed = False
                for i, item in enumerate(trans_value):
                    if i < len(orig_value):
                        restored_item = self._restore_nested_plugin_params(
                            item, orig_value[i], direct_protected_names, plugin_name=plugin_name, parent_key=key
                        )
                        if restored_item != item:
                            list_changed = True
                        new_list.append(restored_item)
                    else:
                        new_list.append(item)
                if list_changed:
                    result['parameters'][key] = new_list
                    self.stats['plugin_params_protected'] += 1

        return result

    def _restore_nested_plugin_params(self, trans_node: Any, orig_node: Any,
                                      protected_keys_set: set, plugin_name: str, parent_key: str) -> Any:
        """Recursively restore values in nested plugin parameter structures (dicts/lists)."""
        if isinstance(trans_node, dict) and isinstance(orig_node, dict):
            result = copy.deepcopy(trans_node)
            for key in list(result.keys()):
                orig_val = orig_node.get(key)
                trans_val = result[key]

                # Direct key protection for this level
                if key in protected_keys_set:
                    if orig_val is not None and trans_val != orig_val:
                        result[key] = copy.deepcopy(orig_val)
                        self.stats['plugin_params_protected'] += 1
                    continue

                # Recursive call for nested dicts/lists
                if isinstance(trans_val, dict) and isinstance(orig_val, dict):
                    result[key] = self._restore_nested_plugin_params(
                        trans_val, orig_val, protected_keys_set, plugin_name, f"{parent_key}.{key}"
                    )
                elif isinstance(trans_val, list) and isinstance(orig_val, list):
                    new_list = []
                    list_changed = False
                    for i, item in enumerate(trans_val):
                        if i < len(orig_val):
                            restored_item = self._restore_nested_plugin_params(
                                item, orig_val[i], protected_keys_set, plugin_name, f"{parent_key}.{key}[{i}]"
                            )
                            if restored_item != item:
                                list_changed = True
                            new_list.append(restored_item)
                        else:
                            new_list.append(item)
                    if list_changed:
                        result[key] = new_list
                        self.stats['plugin_params_protected'] += 1

                # If the value is a string, check if it's a stringified JSON and apply nested protection
                elif isinstance(trans_val, str):
                    nested_protected_keys_for_string = self._get_nested_param_protection(plugin_name, f"{parent_key}.{key}")
                    if nested_protected_keys_for_string is None: # Also check for direct key on the current level for strings
                        nested_protected_keys_for_string = self._get_nested_param_protection(plugin_name, key)

                    if nested_protected_keys_for_string is not None:
                        parsed_trans = self._parse_json_string(trans_val)
                        parsed_orig = self._parse_json_string(orig_val) if isinstance(orig_val, str) else None
                        
                        if parsed_trans is not None and parsed_orig is not None:
                            restored_nested_data = self._restore_nested_json_params(
                                parsed_trans, parsed_orig, set(nested_protected_keys_for_string), plugin_name=plugin_name, parent_key=f"{parent_key}.{key}"
                            )
                            serialized_restored = self._serialize_json_string(restored_nested_data)
                            if serialized_restored != trans_val:
                                result[key] = serialized_restored
                                self.stats['plugin_params_protected'] += 1
                    # Fallback: if it's just a string and no specific nested JSON rule, treat as potential filename
                    elif trans_val != orig_val and self._looks_like_filename(trans_val):
                        result[key] = copy.deepcopy(orig_val)
                        self.stats['filename_params_restored'] += 1

            return result

        elif isinstance(trans_node, list) and isinstance(orig_node, list):
            new_list = []
            list_changed = False
            for i, item in enumerate(trans_node):
                if i < len(orig_node):
                    restored_item = self._restore_nested_plugin_params(
                        item, orig_node[i], protected_keys_set, plugin_name, f"{parent_key}[{i}]"
                    )
                    if restored_item != item:
                        list_changed = True
                    new_list.append(restored_item)
                else:
                    new_list.append(item)
            return new_list if list_changed else trans_node

        elif isinstance(trans_node, str) and isinstance(orig_node, str):
            if trans_node != orig_node and self._looks_like_filename(trans_node):
                self.stats['filename_params_restored'] += 1
                return orig_node
            return trans_node
        
        return copy.deepcopy(trans_node)
        
    def _restore_nested_json_params(self, trans_data: Any, orig_data: Any, 
                                     protected_keys_set: set, plugin_name: str, parent_key: str) -> Any:
        """
        Recursively restores keys/values within a parsed JSON structure (from a string parameter).
        """
        if isinstance(trans_data, dict) and isinstance(orig_data, dict):
            result = copy.deepcopy(trans_data)
            for key in list(result.keys()):
                orig_val = orig_data.get(key)
                trans_val = result[key]

                # If this key is specifically protected for reversion
                if key in protected_keys_set:
                    if orig_val is not None and trans_val != orig_val:
                        result[key] = copy.deepcopy(orig_val)
                        self.stats['plugin_params_protected'] += 1
                    continue
                
                # Recursive call for nested structures within the stringified JSON
                result[key] = self._restore_nested_json_params(
                    trans_val, orig_val, protected_keys_set, plugin_name, f"{parent_key}.{key}"
                )
            return result
        
        elif isinstance(trans_data, list) and isinstance(orig_data, list):
            new_list = []
            list_changed = False
            for i, item in enumerate(trans_data):
                if i < len(orig_data):
                    restored_item = self._restore_nested_json_params(
                        item, orig_data[i], protected_keys_set, plugin_name, f"{parent_key}[{i}]"
                    )
                    if restored_item != item:
                        list_changed = True
                    new_list.append(restored_item)
                else:
                    new_list.append(item)
            return new_list if list_changed else trans_data

        elif isinstance(trans_data, str) and isinstance(orig_data, str):
            if trans_data != orig_data:
                if parent_key.endswith('.animations') or parent_key.endswith('.skeletonName') or self._looks_like_filename(trans_data):
                    self.stats['plugin_params_protected'] += 1
                    return orig_data
            return trans_data
        
        return copy.deepcopy(trans_data)

    def _process_generic_file(self, trans_data: Any, orig_data: Any) -> Any:
        """
        Process other JSON files (actors, classes, items, etc.).
        Reverts any string fields that look like transliterated filenames.
        """
        return self._deep_restore_filenames(trans_data, orig_data)

    def _deep_restore_filenames(self, trans_node: Any, orig_node: Any) -> Any:
        """Recursively walk two data nodes, reverting filename-like strings."""
        if isinstance(trans_node, dict) and isinstance(orig_node, dict):
            result = {}
            for key in trans_node:
                if key in orig_node:
                    result[key] = self._deep_restore_filenames(
                        trans_node[key], orig_node[key]
                    )
                else:
                    result[key] = copy.deepcopy(trans_node[key])
            return result

        if isinstance(trans_node, list) and isinstance(orig_node, list):
            result = []
            max_len = min(len(trans_node), len(orig_node))
            for i in range(max_len):
                result.append(self._deep_restore_filenames(trans_node[i], orig_node[i]))
            if len(trans_node) > max_len:
                result.extend(copy.deepcopy(trans_node[max_len:]))
            return result

        if isinstance(trans_node, str) and isinstance(orig_node, str):
            if trans_node != orig_node and self._looks_like_filename(trans_node):
                self.stats['filename_params_restored'] += 1
                return orig_node

        return copy.deepcopy(trans_node)

    # Param index where filename lives (per engine command code)
    # MZ/MV 250 (Play SE):  params = [name, volume, pitch, pan]
    # MZ/MV 251 (Play ME):  params = [name, volume, pitch, pan]
    # MZ/MV 231 (Show Pic): params = [picNo, name, origin, x, y, ...]
    REVERT_FILENAME_CODES_PARAM_INDEX = {
        '250': 0,  # SE name at index 0
        '251': 0,  # ME name at index 0
        '231': 1,  # Picture name at index 1 (index 0 is picture number)
    }

    def _print_summary(self):
        """Print restoration summary."""
        print("\n" + "=" * 60)
        print("RESTORATION SUMMARY")
        print("=" * 60)
        print(f"  Files processed:          {self.stats['files_processed']}")
        print(f"  Files restored:           {self.stats['files_restored']}")
        print(f"  Commands reverted:        {self.stats['commands_reverted']}")
        print(f"  Filename params restored: {self.stats['filename_params_restored']}")
        print(f"  Plugin params protected:  {self.stats['plugin_params_protected']}")
        print(f"  Forced replacements:     {self.stats['forced_replacements']}")
        print(f"  Warnings/skips:           {self.stats['warnings']}")
        print("=" * 60)


def main():
    # Enforce UTF-8 encoding on Windows console to prevent charmap output crashes
    if sys.platform.startswith('win'):
        import io
        sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding='utf-8', errors='replace')
        sys.stderr = io.TextIOWrapper(sys.stderr.buffer, encoding='utf-8', errors='replace')

    parser = argparse.ArgumentParser(
        description='Universal RPG Maker MV/MZ translation restoration script.',
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Engine-standard rules applied generically (no hardcoded game data):
  401/405/102 -> dialogue (KEPT translated)
  357/355/655 -> plugin commands & scripts (REVERT to original)
  250/251/231 -> audio/picture filenames (REVERT)

Plugin-specific param names and regex patterns live in the external config.
        """
    )
    parser.add_argument('data_original', nargs='?',
                        help='Directory containing original (pre-translation) JSON files.')
    parser.add_argument('data_translated', nargs='?',
                        default=None,
                        help='Directory containing translated JSON files (will be modified in-place).')
    parser.add_argument('config_path', nargs='?',
                        default=None,
                        help='Path to restore_config.json (default: auto-detect).')
    parser.add_argument('--dry-run', action='store_true',
                        help='Report changes without writing files.')
    parser.add_argument('--verbose', action='store_true',
                        help='Show per-file details.')
    parser.add_argument('--standalone', action='store_true',
                        help='Skip diff against backup; apply only generic forced '
                             'PT/ES/FR/DE/IT -> Japanese replacements. Use when no '
                             'original backup exists (e.g. MBFK which has no data_bak_*).')

    args = parser.parse_args()

    # Auto-detect config path
    config_path = args.config_path
    if config_path is None:
        script_dir = os.path.dirname(os.path.abspath(__file__))
        config_candidates = [
            os.path.join(script_dir, 'restore_config.json'),
            os.path.join(script_dir, 'config', 'restore_config.json'),
        ]
        for candidate in config_candidates:
            if os.path.isfile(candidate):
                config_path = candidate
                break
        if config_path is None:
            print("ERROR: Could not auto-detect restore_config.json")
            print("Please specify config path or place restore_config.json")
            print("in the same directory as this script.")
            sys.exit(1)

    try:
        if args.standalone:
            trans_dir = args.data_original
            if not trans_dir or not os.path.isdir(trans_dir):
                print("ERROR: --standalone requires translated dir as first positional (data_original).")
                sys.exit(1)
            restorer = RPGMakerRestorer(
                trans_dir,
                trans_dir,
                config_path,
                dry_run=args.dry_run
            )
            restorer.run_standalone()
        else:
            if not os.path.isdir(args.data_original):
                print("ERROR: data_original is required, or use --standalone.")
                sys.exit(1)
            restorer = RPGMakerRestorer(
                args.data_original,
                args.data_translated,
                config_path,
                dry_run=args.dry_run
            )
            restorer.run()
    except FileNotFoundError as e:
        print(f"ERROR: {e}")
        sys.exit(1)
    except json.JSONDecodeError as e:
        print(f"ERROR: Invalid JSON in config or data file: {e}")
        sys.exit(1)
    except Exception as e:
        print(f"ERROR: {type(e).__name__}: {e}")
        sys.exit(1)


if __name__ == '__main__':
    main()
