/**
 * OpenTranslator — UnityAdapter 2.0
 * Adaptador oficial para jogos desenvolvidos em Unity Engine.
 *
 * Trata separadamente:
 * 1. Unity Mono: Arquitetura .NET com suporte a BepInEx / Doorstop / XUnity runtime bridge
 *    (Apenas configura quando os arquivos do BepInEx realmente existem no disco)
 * 2. Unity IL2CPP: Compilação nativa C++ com fallback inteligente para OCR / Read-Only Diagnostics
 */

const fs = require("fs");
const path = require("path");
const BaseEngineAdapter = require("../../core/baseEngineAdapter");
const CodeProtector = require("../../core/codeProtector");
const BackupManager = require("../../core/backupManager");

class UnityAdapter extends BaseEngineAdapter {
  constructor() {
    super("unity", "Unity Engine");
    this.codeProtector = new CodeProtector("unity");
    this.backupManager = new BackupManager({ backupDirName: ".opent_unity_backup" });
  }

  isIl2cpp(gameDir) {
    if (fs.existsSync(path.join(gameDir, "GameAssembly.dll"))) return true;
    try {
      const entries = fs.readdirSync(gameDir);
      for (const e of entries) {
        if (e.toLowerCase().endsWith("_data") && fs.existsSync(path.join(gameDir, e, "il2cpp_data"))) {
          return true;
        }
      }
    } catch (e) {}
    return false;
  }

  hasBepInEx(gameDir) {
    return fs.existsSync(path.join(gameDir, "BepInEx", "core")) ||
           fs.existsSync(path.join(gameDir, "doorstop_config.ini")) ||
           fs.existsSync(path.join(gameDir, "winhttp.dll"));
  }

  getCapabilities(gameDir, exePath) {
    const isIl2cpp = this.isIl2cpp(gameDir);
    const hasHook = !isIl2cpp && this.hasBepInEx(gameDir);

    return {
      staticFiles: false,
      nativeLocalization: false,
      archives: true,
      runtimeHook: hasHook,
      dom: false,
      frameworkState: false,
      ocr: true,
      backupSupported: true,
      strategy: isIl2cpp ? "OCR / Read-Only Diagnostics" : (hasHook ? "BepInEx Runtime Hook" : "OCR Fallback (Hook Ausente)")
    };
  }

  /**
   * Extrai textos de dicionários de tradução existentes se houver.
   */
  async extract(gameDir, options = {}) {
    const isIl2cpp = this.isIl2cpp(gameDir);
    const transTxt = path.join(gameDir, "AutoTranslator", "Translation", "pt", "Text", "_AutoGeneratedTranslations.txt");
    const allTexts = [];

    if (fs.existsSync(transTxt)) {
      const lines = fs.readFileSync(transTxt, "utf8").split("\n");
      for (const line of lines) {
        const trimmed = line.trim();
        if (trimmed && !trimmed.startsWith("//") && trimmed.includes("=")) {
          const parts = trimmed.split("=");
          const original = parts[0];
          const clean = original.trim();
          if (clean.length > 0) {
            allTexts.push({
              id: allTexts.length,
              file: "_AutoGeneratedTranslations.txt",
              original: clean,
              clean,
              engine: "unity"
            });
          }
        }
      }
    }

    return {
      success: true,
      isIl2cpp,
      texts: allTexts,
      count: allTexts.length,
      warning: isIl2cpp
        ? "Unity IL2CPP detectado. Textos dinâmicos requerem o módulo de OCR em tempo real."
        : (!this.hasBepInEx(gameDir) ? "Unity Mono detectado sem BepInEx pré-instalado. Recomenda-se modo OCR ou instalação do pacote BepInEx." : null)
    };
  }

  async validate(gameDir, texts, translations) {
    return { valid: true, errors: [], warnings: [] };
  }

  /**
   * Aplica a configuração do runtime bridge apenas se os binários do BepInEx estiverem no jogo.
   * NUNCA cria arquivos apontando para DLLs inexistentes.
   */
  async apply(gameDir, texts, translations, options = {}) {
    const isIl2cpp = this.isIl2cpp(gameDir);
    if (isIl2cpp) {
      return {
        success: true,
        modifiedFiles: [],
        count: 0,
        message: "Unity IL2CPP ativo. Modo OCR em tempo real preparado para execução."
      };
    }

    if (!this.hasBepInEx(gameDir)) {
      return {
        success: true,
        modifiedFiles: [],
        count: 0,
        message: "Ambiente BepInEx não instalado na pasta do jogo. Configuração de hook ignorada com sucesso (prevenindo crash)."
      };
    }

    const bepDir = path.join(gameDir, "BepInEx");
    const autoTransConfig = path.join(bepDir, "config", "AutoTranslatorConfig.ini");
    const modifiedFiles = [];

    try {
      if (!fs.existsSync(path.dirname(autoTransConfig))) {
        fs.mkdirSync(path.dirname(autoTransConfig), { recursive: true });
      }

      const iniContent = `[Service]
Endpoint=GoogleTranslate
[General]
Language=pt
FromLanguage=auto
[Files]
Directory=Translation
OutputFile=Translation\\pt\\Text\\_AutoGeneratedTranslations.txt
`;
      if (!fs.existsSync(autoTransConfig)) {
        fs.writeFileSync(autoTransConfig, iniContent, "utf8");
        modifiedFiles.push(autoTransConfig);
      }

      return {
        success: true,
        modifiedFiles,
        count: modifiedFiles.length
      };
    } catch (e) {
      return { success: false, error: e.message, modifiedFiles: [], count: 0 };
    }
  }

  async rollback(gameDir, options = {}) {
    return { success: true, restoredFiles: [] };
  }
}

module.exports = UnityAdapter;
